### ISSUE TITLE
Multiple TypeScript linting errors in apollo-server-express > 2.10.1

### ISSUE THREAD

**Issue by KeithGillette** [apollographql/apollo-server#3992]
After upgrading `apollo-server-express` from v2.10.0 to v2.12.2, I get the following error in running `tslint`:
```
node_modules/apollo-server-express/node_modules/@types/express/index.d.ts:103:54 - error TS2315: Type 'Response' is not generic.

103     export interface Response<ResBody = any> extends core.Response<ResBody> { }
```
I noted that while the [apollo-server-express/package.json](https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-express/package.json#L33) specifies `@types/express@4.17.4`, the actual version installed installed by `npm@6.13.6` in `node_modules/apollo-server-express/package.json` specifies `@types/express@4.17.3`:

```
{
  "_from": "apollo-server-express@latest",
  "_id": "apollo-server-express@2.12.0",
  "_inBundle": false,
  "_integrity": "sha512-oTBKM2SsziCoFW+ta+ubJ/ypvsc+EWrbJnyZhJ5FBYzSXPstt/jvgZHgMO+kOQgHEHrbJwugNDUuLMSm608L7A==",
  "_location": "/apollo-server-express",
  "_phantomChildren": {
    "@types/connect": "3.4.32",
    "@types/express-serve-static-core": "4.16.10",
    "@types/node": "13.11.1",
    "@types/serve-static": "1.13.3"
  },
  "_requested": {
    "type": "tag",
    "registry": true,
    "raw": "apollo-server-express@latest",
    "name": "apollo-server-express",
    "escapedName": "apollo-server-express",
    "rawSpec": "latest",
    "saveSpec": null,
    "fetchSpec": "latest"
  },
  "_requiredBy": [
    "#USER",
    "/"
  ],
  "_resolved": "https://registry.npmjs.org/apollo-server-express/-/apollo-server-express-2.12.0.tgz",
  "_shasum": "a03cef8a3aa753bff73156e6a31fd59a076dc48b",
  "_spec": "apollo-server-express@latest",
  "_where": "/Users/keith.gillette/Code/TaskTrain",
  "author": {
    "name": "opensource@apollographql.com"
  },
  "bugs": {
    "url": "https://github.com/apollographql/apollo-server/issues"
  },
  "bundleDependencies": false,
  "dependencies": {
    "@apollographql/graphql-playground-html": "1.6.24",
    "@types/accepts": "^1.3.5",
    "@types/body-parser": "1.19.0",
    "@types/cors": "^2.8.4",
    "@types/express": "4.17.3",
    "accepts": "^1.3.5",
    "apollo-server-core": "^2.12.0",
    "apollo-server-types": "^0.3.1",
    "body-parser": "^1.18.3",
    "cors": "^2.8.4",
    "express": "^4.17.1",
    "graphql-subscriptions": "^1.0.0",
    "graphql-tools": "^4.0.0",
    "parseurl": "^1.3.2",
    "subscriptions-transport-ws": "^0.9.16",
    "type-is": "^1.6.16"
  },
  "deprecated": false,
  "description": "Production-ready Node.js GraphQL server for Express and Connect",
  "devDependencies": {
    "apollo-server-integration-testsuite": "^2.12.0"
  },
  "engines": {
    "node": ">=6"
  },
  "gitHead": "71a3863f59f4ab2c9052c316479d94c6708c4309",
  "homepage": "https://github.com/apollographql/apollo-server#readme",
  "keywords": [
    "GraphQL",
    "Apollo",
    "Server",
    "Express",
    "Connect",
    "Javascript"
  ],
  "license": "MIT",
  "main": "dist/index.js",
  "name": "apollo-server-express",
  "peerDependencies": {
    "graphql": "^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/apollographql/apollo-server/tree/master/packages/apollo-server-express"
  },
  "types": "dist/index.d.ts",
  "version": "2.12.0"
}
```

**Comment by Tetriando** [comment]
Any updates on this? Still occurs during my local build with latest version (2.14.0)

**Comment by SeijiV13** [comment]
Adding some findings,  this error is still occurring on  compiling node typeorm using apollo-server, I had to downgrade apollo-server from 2.14.0 to 2.10.0 to fix the issue. this is still an existing bug on the latest version.

**Comment by defrex** [comment]
I can confirm this was introduced in `2.12.0`. I've repro'd in `2.12.0`, `2.13.1`, `2.14.4`, and `2.15.0`.

`2.11.0` works as expected.

**Comment by KeithGillette** [comment]
Still not resolved in 2.15.1.

**Comment by KeithGillette** [comment]
Testing `v2.17.0` reveals additional linting errors:
```
node_modules/apollo-server-express/node_modules/@types/express/index.d.ts:98:128 - error TS2694: Namespace '"node_modules/@types/express-serve-static-core/index"' has no exported member 'Query'.

98     interface ErrorRequestHandler<P extends core.Params = core.ParamsDictionary, ResBody = any, ReqBody = any, ReqQuery = core.Query>

node_modules/apollo-server-express/node_modules/@types/express/index.d.ts:99:17 - error TS2707: Generic type 'ErrorRequestHandler' requires between 0 and 1 type arguments.

99         extends core.ErrorRequestHandler<P, ResBody, ReqBody, ReqQuery> { }

node_modules/apollo-server-express/node_modules/@types/express/index.d.ts:108:116 - error TS2694: Namespace '"node_modules/@types/express-serve-static-core/index"' has no exported member 'Query'.

108     interface Request<P extends core.Params = core.ParamsDictionary, ResBody = any, ReqBody = any, ReqQuery = core.Query> extends core.Request<P, ResBody, ReqBody, ReqQuery> { }
                                                                                                                       ~~~~~

node_modules/apollo-server-express/node_modules/@types/express/index.d.ts:108:131 - error TS2707: Generic type 'Request<P>' requires between 0 and 1 type arguments.

108     interface Request<P extends core.Params = core.ParamsDictionary, ResBody = any, ReqBody = any, ReqQuery = core.Query> extends core.Request<P, ResBody, ReqBody, ReqQuery> { }

node_modules/apollo-server-express/node_modules/@types/express/index.d.ts:109:123 - error TS2694: Namespace '"node_modules/@types/express-serve-static-core/index"' has no exported member 'Query'.

109     interface RequestHandler<P extends core.Params = core.ParamsDictionary, ResBody = any, ReqBody = any, ReqQuery = core.Query> extends core.RequestHandler<P, ResBody, ReqBody, ReqQuery> { }

node_modules/apollo-server-express/node_modules/@types/express/index.d.ts:109:138 - error TS2707: Generic type 'RequestHandler<P>' requires between 0 and 1 type arguments.

109     interface RequestHandler<P extends core.Params = core.ParamsDictionary, ResBody = any, ReqBody = any, ReqQuery = core.Query> extends core.RequestHandler<P, ResBody, ReqBody, ReqQuery> { }

node_modules/apollo-server-express/node_modules/@types/express/index.d.ts:111:54 - error TS2315: Type 'Response' is not generic.

111     export interface Response<ResBody = any> extends core.Response<ResBody> { }
```

**Comment by Tetriando** [comment]
@KeithGillette 
Seems to be working now properly with latest v2.18.0 version. At least for me.

**Comment by KeithGillette** [comment]
Thanks for the heads-up @Tetriando. I just updated and confirm that `apollo-server-express@2.18.0` lints without error.
