### ISSUE TITLE
Error when importing PubSub from 'apollo-server-fastify' (nest.js + fastify)

### ISSUE THREAD

**Issue by gcherem** [apollographql/apollo-server#4482]
"apollo-server-fastify": "^2.16.1"
"@nestjs/platform-fastify": "^7.4.2",

Using nestjs + fastify.

When I run the application, I get the following error:

```
node_modules/apollo-server-fastify/dist/ApolloServer.d.ts:8:42 - error TS2559: Type 'IncomingMessage' has no properties in common with type 'RouteGenericInterface'.

8     onHealthCheck?: (req: FastifyRequest<IncomingMessage>) => Promise<any>;
                                           ~~~~~~~~~~~~~~~
node_modules/apollo-server-fastify/dist/ApolloServer.d.ts:14:57 - error TS2559: Type 'IncomingMessage' has no properties in common with type 'RouteGenericInterface'.

14     createGraphQLServerOptions(request?: FastifyRequest<IncomingMessage>, reply?: FastifyReply<OutgoingMessage>): Promise<GraphQLOptions>;
                                                           ~~~~~~~~~~~~~~~
node_modules/apollo-server-fastify/dist/ApolloServer.d.ts:14:96 - error TS2344: Type 'OutgoingMessage' does not satisfy the constraint 'RawServerBase'.
  Type 'OutgoingMessage' is missing the following properties from type 'Http2SecureServer': addContext, getTicketKeys, setSecureContext, setTicketKeys, and 9 more.

14     createGraphQLServerOptions(request?: FastifyRequest<IncomingMessage>, reply?: FastifyReply<OutgoingMessage>): Promise<GraphQLOptions>;
                                                                                                  ~~~~~~~~~~~~~~~

Found 3 error(s).
```

**Comment by gcherem** [comment]
Is there a workaround? Should I downgrade something?

**Comment by abernix** [comment]
Please see the update I just posted on https://github.com/apollographql/apollo-server/pull/4356#issuecomment-677515901 for the availability of the Fastify v3 support on Apollo Server and please note that `PubSub` would be available from `graphql-subscriptions`.  Happy to re-open if this is still a problem after updating to v3.
