### PR TITLE
Updated Cloud Functions README to reflect package name

### PR DESCRIPTION
**Pull request by thetre97**
The package name was different to this README, so I have updated the latter to reflect the actual package name - [apollo-server-cloud-function*s*](https://www.npmjs.com/package/apollo-server-cloud-functions)

TODO:

* [x] Update CHANGELOG.md with your change (include reference to issue & this PR)
* [x] Make sure all of the significant new logic is covered by tests
* [x] Rebase your changes on master so that they can be merged easily
* [x] Make sure all tests and linter rules pass

### CODE REVIEW

**Comment by pyros2097** [comment]
@thetre97 The package is not compiled to js and because of that I couldn't import it in my function. Did you find and way to make it work?

**Comment by thetre97** [comment]
I used the NPM package, which is called [apollo-server-cloud-functions](https://www.npmjs.com/package/apollo-server-cloud-functions), rather than 'apollo-server-cloud-function' (note the missing 's') as the guide says, hence I added this PR to update it.

So I did:

```sh
yarn add apollo-server-cloud-functions
```

and

```javascript
const { ApolloServer, gql } = require('apollo-server-cloud-functions');
```

Then it worked fine with GC Functions Node8 runtime.

Not sure if that is what you mean?

**Comment by pyros2097** [comment]
Yes I know even I made the same PR for the README. Thanks.

What version of the package is it? This is how it looks for me. No index.js file.
ls node_modules/apollo-server-cloud-functions/src/
ApolloServer.ts		__tests__		googleCloudApollo.ts	index.ts


This is the version "_id": "apollo-server-cloud-functions@2.2.0

**Comment by thetre97** [comment]
Ah, i see - sorry.

I was just using version 2.1.0 and I had no problems with it - everything worked fine.
Not sure if 2.2.0 changed something?

**Comment by thetre97** [comment]
You are right -  have just upgraded my function to v2.2.0, and it throws this error -

```sh
ERROR: (gcloud.functions.deploy) OperationError: code=3, message=Function load error: Code in file index.js can't be loaded.
Did you list all required modules in the package.json dependencies?
Detailed stack trace: Error: Cannot find module 'apollo-server-cloud-functions'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/srv/index.js:3:26)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

Try using v2.1.0 and see if it works for you?

**Comment by abernix** [comment]
https://github.com/apollographql/apollo-server/pull/1936 actually fixed most of these, but it appears that the actual directory for the package has been wrong since it was originally introduced in #1446.  This has likely caused the problems you're seeing above.  I'll fix that in another PR, but thanks for raising this!

**Comment by abernix** [comment]
See #1948 for the suspected solution to https://github.com/apollographql/apollo-server/pull/1896#issuecomment-437007086.  Thanks for reporting this!
