### ISSUE TITLE
Error: Cannot find module 'core-js/modules/es7.object.entries'

### ISSUE THREAD

**Issue by wawhal** [apollographql/apollo-server#1542]
I am trying to serve an executable schema. I get the following error while using version `2.0.2`. Works totally fine with version `2.0.0`.

```
Error: Cannot find module 'core-js/modules/es7.object.entries'
    at Object.<anonymous> (/home/wawhal/oss/schema-stitching-examples/multiple-remote-graphql-apis/node_modules/apollo-upload-server/lib/middleware.js:14:1)
```

/label bug

**Comment by nicholasxuu** [comment]
official getting-started example shows the same error.

https://www.apollographql.com/docs/apollo-server/getting-started.html

**Comment by andyrichardson** [comment]
I am having the same problem using apollo-server-express.

The issue seems to be caused by the peer dependency `apollo-upload-server` ([see related issue here](https://github.com/jaydenseric/apollo-upload-server/issues/103)).

**Comment by yellowiscool** [comment]
A temporary workaround : `npm install core-js`

**Comment by abenhamdine** [comment]
hmm `npm install apollo-server-express@2.0.5` fails because version unfound, it doesn't look published yet.

**Comment by abernix** [comment]
@abenhamdine Sorry, you're right, I should have just said "it's fixed in `latest`" since the integration packages have independent versioning now to avoid bumping _all_ integrations versions when only one of the underlying integration frameworks has changed (e.g. if only `express`'s API changed, we'd have had to confusingly bump `apollo-server-hapi`s version too).  Thanks for pointing this out!

**Comment by human-a** [comment]
This is still not fixed for ```apollo-server-koa@rc``` which seems to be left behind from other apollo-server integrations!

**Comment by abernix** [comment]
@human-a The official release of `apollo-server` and `apollo-server-koa` 2.x has come out and neither are still in the release-candidate phase.  However, the `rc` tag still points to the last release candidate version of `apollo-server-koa`.  I believe if you'd like to get this fix, you'd need to move to the `latest` tag.  The `rc` tag will likely remain pointed to the last 2.x RC until the next series of release candidate testing begins — most likely to occur whenever `apollo-server-*` 2.1.x packages mature to an RC state.

That is to say, can you try with `apollo-server-koa@2.0.4` – as of this writing, the `latest`/most recent version?

**Comment by human-a** [comment]
Awesome! thanks :)

**Comment by zainulabidin302** [comment]
After upgrading to 2.3.3, I got the same error again. Downgrading to 2.0.4 fixed it.

**Comment by marcel-devdude** [comment]
Same here 😞

**Comment by eliotis** [comment]
Same here but with following error: 
"Error: Cannot find module 'core-js/proposals/array-flat-and-flat-map"
Fixed by downgrading to 2.0.7

**Comment by giovangonzalez** [comment]
I'm using apollo-server-express 2.2.6 and yarn install, any idea about how to solve this? I have another project with same base code and package version and it is working!

**Comment by abernix** [comment]
@giovangonzalez Please update to a newer version of Apollo Server and see if the problem is still occurring.  If it is, please open a new issue with a runnable reproduction, per the instructions when opening a new issue.  Thanks!
