### ISSUE TITLE
regression from 2.0.0-beta.7 in 2.0.0-beta.8

### ISSUE THREAD

**Issue by jardakotesovec** [apollographql/apollo-server#1170]
Just migrated from version 1 to version 2.  It works fine with 2.0.0-beta.7. But with beta.8 I was getting

```
Invalid options provided to ApolloServer: (intermediate value).graphQLServerOptions is not a function
```

I was using very similar set up to the [basic example](https://www.apollographql.com/docs/apollo-server/v2/migration-two-dot.html#apollo-server-2), so there is good chance that you will be able to reproduce it. 

This issue is mainly to save others time if they are getting this error.
